site_name: "Brax Open Source"
site_description: "Official Brax Technologies Open Source Handbook – Vision, Processes, and People Growth"
site_author: "Brax Technologies"
site_url: "https://opensource.braxtech.net/"

docs_dir: docs
site_dir: site
watch:
  - docs

theme:
  name: "material"
  language: "en"
  features:
    - navigation.tabs
    - navigation.expand
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.integrate
    - content.code.copy
    - content.code.annotate
    - content.action.edit
    - content.action.view
    - search.suggest
    - search.highlight
    - navigation.footer
  palette:
    - scheme: default
      primary: black
      accent: deep orange
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: black
      accent: deep orange
  font:
    text: "Inter"
    code: "JetBrains Mono"
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico

nav:
  - Welcome: index.md

  - Manifesto: manifesto/index.md

  - For Developers:
      - Overview: for-developers/index.md
      - BraX3:
          - iodéOS:
              - Overview: for-developers/BraX3/iodeos/index.md
              - About: for-developers/BraX3/iodeos/about.md
              - Download: for-developers/BraX3/iodeos/download.md
              - Repositories: for-developers/BraX3/iodeos/repositories.md
              - Build: for-developers/BraX3/iodeos/build.md
              - Test: for-developers/BraX3/iodeos/test.md
              - Contribute: for-developers/BraX3/iodeos/contribute.md
              - Issue Board: for-developers/BraX3/iodeos/issue-board.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - def_list
  - tables
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.smartsymbols
  - pymdownx.caret
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.mark
  - pymdownx.keys

plugins:
  - search
  - tags
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - minify:
      minify_html: true
  - live-edit
  - mkdocs-pdf

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/braxtechnologies/brax-docs
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/brax-technologies/
    - icon: fontawesome/solid/globe
      link: https://community.braxtech.net/
    - icon: fontawesome/brands/twitter
      link: https://x.com/BraxSocial

use_directory_urls: false
repo_url: "https://github.com/braxtechnologies/brax-docs"
repo_name: "braxtechnologies/brax-docs"
edit_uri: "edit/dev/docs/"
