# Configuration for Zensical (https://zensical.org)
# Zensical is a modern static site generator built by the creators of Material for MkDocs

[project]
site_name = "Open Source Community Guide"
site_url = "https://opensource.braxtech.net/"
site_description = "Official Brax Technologies Open Source Handbook – Vision, Processes, and People Growth"
site_author = "Brax Technologies"
repo_url = "https://github.com/braxtechnologies/brax-docs"
repo_name = "braxtechnologies/brax-docs"
edit_uri = "edit/dev/docs/"


[directories]
docs = "docs"
site = "site"
watch = ["docs"]


[project.theme]
name = "material"
language = "en"
logo = "assets/images/logo.svg"
favicon = "assets/images/favicon.ico"
nav_order= ["Home", "Devices", "Manifesto", "Governance", "Bounties", "Careers", "Partners", "Guide", "Apps", "Brax Network", "Events", "Employee Handbook"]
features = [
"navigation.tabs",
"navigation.instant",
"navigation.instant.prefetch",
"navigation.instant.progress",
"navigation.tracking",
"navigation.tabs.sticky",
"navigation.sections",
"navigation.path",
"navigation.footer",
"content.action.edit", # Edit this page
"content.action.view"  # View source of this page
]

[[theme.palette]]
scheme = "default"
primary = "black"
accent = "deep orange"

[[theme.palette]]
scheme = "slate"
primary = "black"
accent = "deep orange"

[theme.palette.toggle]
icon = "material/weather-night"
name = "Switch to dark mode"

[theme.font]
text = "Inter"
code = "JetBrains Mono"


[nav]
[nav."Home"]
"Welcome" = "index.md"

[nav."Devices"]
"Overview" = "devices/index.md"

[nav."Devices"."BraX3"."Overview"]
"Overview" = "devices/BraX3/Overview/index.md"
"Unlock Bootloader" = "devices/BraX3/Overview/unlock-bootloader.md"
"Manual Install/Update OS" = "devices/BraX3/Overview/manual-install-update-os.md"

[nav."Devices"."BraX3"."Repair Guide"]
"Overview" = "devices/BraX3/RepairGuide/index.md"
"Screen Replacement" = "devices/BraX3/RepairGuide/screen-replacement.md"
"Battery Replacement" = "devices/BraX3/RepairGuide/battery-replacement.md"
"Charging Port Repair" = "devices/BraX3/RepairGuide/charging-port-repair.md"
"Button Replacement" = "devices/BraX3/RepairGuide/button-replacement.md"

[nav."Devices"."BraX3"."Supported OS"."AOSP"]
"" = "devices/BraX3/SupportedOS/AOSP/index.md"

[nav."Devices"."BraX3"."Supported OS"."BraxOS"]
"" = "devices/BraX3/SupportedOS/BraxOS/index.md"

[nav."Devices"."BraX3"."Supported OS"."CypherOS"]
"Overview" = "devices/BraX3/SupportedOS/CypherOS/index.md"

[nav."Devices"."BraX3"."Supported OS"."iodéOS"]
"" = "devices/BraX3/SupportedOS/iodeos/index.md"

[nav."Devices"."BraX3"."Supported OS"."LineageOS"]
"Overview" = "devices/BraX3/SupportedOS/LineageOS/index.md"

[nav."Devices"."BraX3"."Supported OS"."LunarOS"]
"" = "devices/BraX3/SupportedOS/LunarOS/index.md"

[nav."Devices"."BraX3"."Supported OS"."Ubuntu Touch"]
"" = "devices/BraX3/SupportedOS/ubuntu-touch/index.md"

[nav."Manifesto"]
"" = "manifesto/index.md"

[nav."Governance"]
"Overview" = "governance/index.md"

[nav."Governance"."Code of Conduct"]
"Overview" = "governance/code-of-conduct/index.md"
"Conflict Resolution" = "governance/code-of-conduct/conflict-resolution.md"

[nav."Governance"."Corporate Structure"]
"" = "governance/Corporate Structure/index.md"

[nav."Governance"."Social and Environmental Impact"]
"" = "governance/Social and Environmental Impact/index.md"

[nav."Governance"."Project Governance"]
"Overview" = "governance/Project Governance/index.md"
"Code of Conduct" = "governance/Project Governance/code_of_conduct.md"
"Contributing" = "governance/Project Governance/contributing.md"

[nav."Governance"."Management Model"]
"Overview" = "governance/Management Model and Employee Handbook/index.md"
"About Us" = "governance/Management Model and Employee Handbook/about-us.md"
"Vision, Mission & Focus" = "governance/Management Model and Employee Handbook/vision-mission-focus.md"
"How We Make Decisions" = "governance/Management Model and Employee Handbook/how-we-make-decisions.md"
"Leadership" = "governance/Management Model and Employee Handbook/HOW WE MAKE DECISIONS/Leadership.md"
"Strategy" = "governance/Management Model and Employee Handbook/HOW WE MAKE DECISIONS/Strategy.md"
"Team Management" = "governance/Management Model and Employee Handbook/HOW WE MAKE DECISIONS/Team Management.md"

[nav."Bounties"]
"" = "bounties/index.md"

[nav."Careers"]
"" = "careers/index.md"

[nav."Partners"]
"" = "partners/index.md"

[nav."Guide"]
"Guide" = "blog/index.md"

[nav."Apps"]
"Overview" = "apps/index.md"
"Brax Chat" = "apps/brax-chat.md"
"Brax Vault" = "apps/brax-vault.md"
"APK Station" = "apps/apk-station.md"

[nav."Brax Network"]
"Overview" = "brax-network/index.md"
"Overview Details" = "brax-network/overview.md"
"Architecture" = "brax-network/architecture.md"
"Deployment" = "brax-network/deployment.md"
"Security & Privacy" = "brax-network/security.md"
"Compliance" = "brax-network/compliance.md"
"Roadmap" = "brax-network/roadmap.md"

[nav."Events"]
"Overview" = "events/index.md"

[nav."Events"."Upcoming Events"]
"Open Source Experience 2025" = "events/upcoming-events/opensource-experience-2025.md"

[nav."Events"."Community Events"]
"" = "events/community-events/index.md"

[nav."Events"."Past Events"]
"" = "events/past-events/index.md"

[nav."Employee Handbook"]
"Overview" = "Employee Handbook/index.md"

[nav."Employee Handbook"."About Us"]
"" = "Employee Handbook/about-us/index.md"

[nav."Employee Handbook"."How We Make Decisions"]
"Strategy" = "Employee Handbook/how-we-make-decisions/strategy/index.md"
"Context, not control" = "Employee Handbook/how-we-make-decisions/strategy/context-not-control.md"
"Strategic management" = "Employee Handbook/how-we-make-decisions/strategy/strategic-management.md"
"Culture code" = "Employee Handbook/how-we-make-decisions/strategy/culture-code.md"
"Leadership" = "Employee Handbook/how-we-make-decisions/leadership/index.md"
"Managers" = "Employee Handbook/how-we-make-decisions/leadership/managers.md"
"Tech leads" = "Employee Handbook/how-we-make-decisions/leadership/tech-leads.md"
"Traits of leadership" = "Employee Handbook/how-we-make-decisions/leadership/traits-of-leadership.md"
"Leaders Performance" = "Employee Handbook/how-we-make-decisions/leadership/leaders-performance.md"
"Team management" = "Employee Handbook/how-we-make-decisions/team-management/index.md"
"Team Structure" = "Employee Handbook/how-we-make-decisions/team-management/team-structure-designed-for-success.md"
"Effective Ceremonies" = "Employee Handbook/how-we-make-decisions/team-management/embracing-effective-ceremonies.md"
"Strategic Sessions" = "Employee Handbook/how-we-make-decisions/team-management/strategic-sessions-empowering-innovation.md"

[nav."Employee Handbook"."How We Build"]
"Operations and roles" = "Employee Handbook/how-we-build-processes-and-a-great-product/operations-and-roles/index.md"
"Growth and Complexity" = "Employee Handbook/how-we-build-processes-and-a-great-product/operations-and-roles/how-we-navigate-growth-and-complexity.md"
"RACI & CODE-KS" = "Employee Handbook/how-we-build-processes-and-a-great-product/operations-and-roles/our-responsibility-assignment-matrixes-raci-and-code-ks.md"
"Knowledge management" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/index.md"
"Knowledge Categories" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/knowledge-categories.md"
"Knowledge Accountability" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/knowledge-accountability-index.md"
"Confluence" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/confluence.md"
"Learning day" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/learning-day.md"
"Knowledge Centricity" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/company-knowledge-centricity-level.md"
"Realms" = "Employee Handbook/how-we-build-processes-and-a-great-product/knowledge-management/realms.md"
"Engineering culture" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/index.md"
"Team culture" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/team-culture.md"
"Process and Roles" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/engineering-process-and-roles.md"
"Team Events" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/team-events-and-processes/index.md"
"Scrum Events" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/team-events-and-processes/scrum-events.md"
"Ongoing Meetings" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/team-events-and-processes/ongoing-meetings.md"
"Concepts" = "Employee Handbook/how-we-build-processes-and-a-great-product/engineering-culture/team-events-and-processes/concepts.md"

[nav."Employee Handbook"."People Growth"]
"Performance" = "Employee Handbook/how-we-ensure-peoples-growth/performance/index.md"
"Paths" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/index.md"
"IC Path" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/individual-contributors-path/index.md"
"IC Levels" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/individual-contributors-path/individual-contributors-levels-software-engineering.md"
"IC Steps" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/individual-contributors-path/individual-contributors-steps.md"
"Management Path" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/management-path/index.md"
"Level 1 Pace setters" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/management-path/level-1-our-pace-setters.md"
"Level 2 Coaches" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/management-path/level-2-our-coaches.md"
"Level 3 Visionaries" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/management-path/level-3-our-visionaries-and-servant-leaders.md"
"Level 4 Leaders" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/management-path/level-4-our-transformational-leaders.md"
"Key concepts" = "Employee Handbook/how-we-ensure-peoples-growth/performance/paths/management-path/key-concepts.md"
"Performance evaluation" = "Employee Handbook/how-we-ensure-peoples-growth/performance/performance-evaluation.md"
"360 Evaluation" = "Employee Handbook/how-we-ensure-peoples-growth/performance/360-evaluation-matrix.md"
"K-POC" = "Employee Handbook/how-we-ensure-peoples-growth/performance/k-poc.md"
"CAP" = "Employee Handbook/how-we-ensure-peoples-growth/performance/cap.md"
"Golden Rules" = "Employee Handbook/how-we-ensure-peoples-growth/performance/management-model-golden-rules.md"
"Compensation" = "Employee Handbook/how-we-ensure-peoples-growth/compensation/index.md"
"IC Frameworks" = "Employee Handbook/how-we-ensure-peoples-growth/compensation/ic-frameworks/index.md"
"MGT Frameworks" = "Employee Handbook/how-we-ensure-peoples-growth/compensation/mgt-frameworks/index.md"
"Empowering Growth" = "Employee Handbook/how-we-ensure-peoples-growth/empowering-growth-through-transparent-management-your-path-to-success.md"

[nav."Employee Handbook"."Policies"]
"Internal rules" = "Employee Handbook/policies/internal-rules/index.md"
"Salaries" = "Employee Handbook/policies/salaries.md"
"brax knowledge" = "Employee Handbook/policies/brax-knowledge.md"
"Sources" = "Employee Handbook/policies/sources.md"
"Glossary" = "Employee Handbook/policies/glossary.md"

[markdown]
extensions = [
    "toc",
    "admonition",
    "footnotes",
    "def_list",
    "tables",
    "attr_list",
    "md_in_html",
    "pymdownx.details",
    "pymdownx.superfences",
    "pymdownx.tabbed",
    "pymdownx.emoji",
    "pymdownx.highlight",
    "pymdownx.inlinehilite",
    "pymdownx.snippets",
    "pymdownx.smartsymbols",
    "pymdownx.caret",
    "pymdownx.tilde",
    "pymdownx.tasklist",
    "pymdownx.mark",
    "pymdownx.keys",
]

[markdown.extension_configs]
toc = { permalink = true }
"pymdownx.tabbed" = { alternate_style = true }
"pymdownx.emoji" = { emoji_index = "material.extensions.emoji.twemoji", emoji_generator = "material.extensions.emoji.to_svg" }
"pymdownx.tasklist" = { custom_checkbox = true }

[plugins]
search = {}
typeset = {}
tags = {}


[plugins.git-revision-date-localized]
fallback_to_build_date = true

[plugins.glightbox]


[plugins.live-edit]

[plugins.mkdocs-pdf]

[project.extra.consent]
title = "Cookie consent"
description = """
    We use cookies to recognize your repeated visits and preferences, as well
    as to measure the effectiveness of our documentation and whether users
    find what they're searching for. With your consent, you're helping us to
    make our documentation better.
"""

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/braxtechnologies/brax-docs"

[[project.extra.social]]
icon = "fontawesome/brands/linkedin"
link = "https://www.linkedin.com/company/brax-technologies/"

[[project.extra.social]]
icon = "fontawesome/solid/globe"
link = "https://community.braxtech.net/"

[[project.extra.social]]
icon = "fontawesome/brands/twitter"
link = "https://x.com/BraxSocial"


[settings]
use_directory_urls = false
